# Minecraft Entity Manager
# Made by Jack Donofrio

# All values are true by default
AREA_EFFECT_CLOUD: true
ARMOR_STAND: true
ARROW: true
BAT: true
BEE: true
BLAZE: true
BOAT: true
CAT: true
CAVE_SPIDER: true
CHICKEN: true
COD: true
COW: true
CREEPER: true
DOLPHIN: true
DONKEY: true
DRAGON_FIREBALL: true
DROPPED_ITEM: true
DROWNED: true
EGG: true
ELDER_GUARDIAN: true
ENDER_CRYSTAL: true
ENDER_PEARL: true
ENDER_SIGNAL: true
ENDERMAN: true
ENDERMITE: true
EVOKER: true
EVOKER_FANGS: true
EXPERIENCE_ORB: true
FALLING_BLOCK: true
FIREBALL: true
FIREWORK: true
FISHING_HOOK: true
FOX: true
GHAST: true
GIANT: true
GUARDIAN: true
HOGLIN: true
HORSE: true
ILLUSIONER: true
IRON_GOLEM: true
ITEM_FRAME: true
LEASH_HITCH: true
LIGHTNING: true
LLAMA: true
LLAMA_SPIT: true
MAGMA_CUBE: true
MINECART: true
MINECART_CHEST: true
MINECART_COMMAND: true
MINECART_FURNACE: true
MINECART_HOPPER: true
MINECART_MOB_SPAWNER: true
MINECART_TNT: true
MULE: true
MUSHROOM_COW: true
OCELOT: true
PAINTING: true
PANDA: true
PARROT: true
PHANTOM: true
PIG: true
PIGLIN: true
PIG_ZOMBIE: true
PILLAGER: true
POLAR_BEAR: true
PRIMED_TNT: true
PUFFERFISH: true
RABBIT: true
RAVAGER: true
SALMON: true
SHEEP: true
SHULKER: true
SHULKER_BULLET: true
SILVERFISH: true
SKELETON: true
SKELETON_HORSE: true
SLIME: true
SMALL_FIREBALL: true
SNOWBALL: true
SNOWMAN: true
SPECTRAL_ARROW: true
SPIDER: true
SPLASH_POTION: true
SQUID: true
STRAY: true
STRIDER: true
THROWN_EXP_BOTTLE: true
TRADER_LLAMA: true
TRIDENT: true
TROPICAL_FISH: true
TURTLE: true
VEX: true
VILLAGER: true
VINDICATOR: true
WANDERING_TRADER: true
WITCH: true
WITHER: true
WITHER_SKELETON: true
WITHER_SKULL: true
WOLF: true
ZOGLIN: true
ZOMBIE: true
ZOMBIE_HORSE: true
ZOMBIE_VILLAGER: true
ZOMBIFIED_PIGLIN: true
