name: EntityManager
main: com.gmail.jackdonofrio12.EntityManager
version: 1.0
api-version: 1.13
commands:
   disable:
      description: disables the spawning of a given entity
      permission: entitymanager.disable
      usage: /<command> (entity name)
   enable:
      description: enables the spawning of a given entity
      permission: entitymanager.enable
      usage: /<command> (entity name)
permissions:
   entitymanager.enable:
      description: Allows you to enable the spawning of a given entity.
      default: op
   entitymanager.disable:
      description: Allows you to disable spawning of a given entity
      default: op